"""initial_migrations

Revision ID: 0001
Revises: 
Create Date: 2024-08-07 21:38:21.045580

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    comment='Информация о пользователе telegram.'
    )
    op.create_table('cl_news_category',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cl_news_source_type',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cl_parse_expression_type',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nf_news_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('update_interval', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('default_news_category_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['default_news_category_id'], ['cl_news_category.id'], ),
    sa.ForeignKeyConstraint(['source_type_id'], ['cl_news_source_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nf_news',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('news_url', sa.Text(), nullable=False),
    sa.Column('news_source_id', sa.Uuid(), nullable=False),
    sa.Column('news_category_id', sa.SmallInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['news_category_id'], ['cl_news_category.id'], ),
    sa.ForeignKeyConstraint(['news_source_id'], ['nf_news_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_url')
    )
    op.create_table('nf_parsing_expressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parse_expression_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('parse_expression', sa.Text(), nullable=False),
    sa.Column('news_source_id', sa.Uuid(), nullable=False),
    sa.Column('parsing_level', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['news_source_id'], ['nf_news_source.id'], ),
    sa.ForeignKeyConstraint(['parse_expression_type_id'], ['cl_parse_expression_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nf_user_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('news_source_id', sa.Uuid(), nullable=True),
    sa.Column('news_category_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['news_category_id'], ['cl_news_category.id'], ),
    sa.ForeignKeyConstraint(['news_source_id'], ['nf_news_source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nf_news_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['nf_news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_news_images')
    op.drop_table('nf_user_subscription')
    op.drop_table('nf_parsing_expressions')
    op.drop_table('nf_news')
    op.drop_table('nf_news_source')
    op.drop_table('cl_parse_expression_type')
    op.drop_table('cl_news_source_type')
    op.drop_table('cl_news_category')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
