"""initial_migrations

Revision ID: 0001
Revises: 
Create Date: 2024-08-24 13:44:12.904515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя в телеграм'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='Информация о пользователе telegram.'
    )
    op.create_table('cl_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор категории новостей'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование новостной категории'),
    sa.Column('deletion_datetime', sa.DateTime(), nullable=True, comment='Дата удаления'),
    sa.PrimaryKeyConstraint('id'),
    comment='Категории для новостей.'
    )
    op.create_table('cl_parsers',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор парсера'),
    sa.Column('name', sa.String(length=120), nullable=True, comment='Название парсера'),
    sa.Column('parser_class', sa.String(length=120), nullable=True, comment='Класс парсера'),
    sa.PrimaryKeyConstraint('id'),
    comment='Модель содержащая класс и имя парсера.'
    )
    op.create_table('cl_resource_type',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Идентификатор типа источника новостей'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование типа источника новостей'),
    sa.PrimaryKeyConstraint('id'),
    comment='Тип источника новости.'
    )
    op.create_table('cl_roles',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Идентификатор роли'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Роль'),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор ролей пользователя.'
    )
    op.create_table('nf_news',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор новости'),
    sa.Column('title', sa.Text(), nullable=False, comment='Заголовок новости'),
    sa.Column('description', sa.Text(), nullable=True, comment='Краткий анонс новости'),
    sa.Column('content', sa.Text(), nullable=True, comment='Текст новости'),
    sa.Column('news_url', sa.Text(), nullable=False, comment='Ссылка на новость'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='Дата публикации'),
    sa.Column('detected_at', sa.DateTime(), nullable=False, comment='Дата добавления в базу'),
    sa.Column('author', sa.Text(), nullable=True, comment='Информация об авторе'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_url'),
    comment='Новости.'
    )
    op.create_table('bot_news_sent',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['nf_news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Информация об отправленных новостях.'
    )
    op.create_table('bot_user_roles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя телеграм'),
    sa.Column('role_id', sa.SmallInteger(), nullable=False, comment='Идентификатор роли'),
    sa.ForeignKeyConstraint(['role_id'], ['cl_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Роли пользователя.'
    )
    op.create_table('nf_images',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['nf_news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Изображения к новостям.'
    )
    op.create_table('nf_resources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор новостного ресурса'),
    sa.Column('url', sa.Text(), nullable=False, comment='Адрес новостного ресурса'),
    sa.Column('update_interval', sa.Interval(), nullable=False, comment='Частота обновления в секундах'),
    sa.Column('update_datetime', sa.DateTime(), nullable=True, comment='Дата и время последнего обновления'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название новостного ресурса'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий'),
    sa.Column('parser_id', sa.Integer(), nullable=False, comment='Идентификатор парсера'),
    sa.Column('source_type_id', sa.SmallInteger(), nullable=False, comment='Идентификатор типа новостного ресурса'),
    sa.ForeignKeyConstraint(['parser_id'], ['cl_parsers.id'], ),
    sa.ForeignKeyConstraint(['source_type_id'], ['cl_resource_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    comment='Источники новостей.'
    )
    op.create_table('nf_remote_categories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор категории ресурса'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.Column('url', sa.Text(), nullable=False, comment='Ссылка на категорию'),
    sa.Column('news_resource_id', sa.Uuid(), nullable=False),
    sa.Column('update_interval', sa.Interval(), nullable=True, comment='Интервал обновление в секундах'),
    sa.Column('update_datetime', sa.DateTime(), nullable=True, comment='Дата и время последнего обновления'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Локальная категория новостей'),
    sa.Column('parser_id', sa.Integer(), nullable=True, comment='Идентификатор парсера'),
    sa.Column('deletion_datetime', sa.DateTime(), nullable=True, comment='Дата и время удаления'),
    sa.Column('notification_datetime', sa.DateTime(), nullable=True, comment='Дата и время когда было выслано уведомление о добавлении категории'),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.ForeignKeyConstraint(['news_resource_id'], ['nf_resources.id'], ),
    sa.ForeignKeyConstraint(['parser_id'], ['cl_parsers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Категории новостей на новостном ресурсе.'
    )
    op.create_table('nf_user_subscription',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['nf_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Подписки пользователя.'
    )
    op.create_table('nf_news_remote_categories',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Идентификатор'),
    sa.Column('remote_category_id', sa.Uuid(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['nf_news.id'], ),
    sa.ForeignKeyConstraint(['remote_category_id'], ['nf_remote_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица для связи многий ко многим новостей с категориями.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nf_news_remote_categories')
    op.drop_table('nf_user_subscription')
    op.drop_table('nf_remote_categories')
    op.drop_table('nf_resources')
    op.drop_table('nf_images')
    op.drop_table('bot_user_roles')
    op.drop_table('bot_news_sent')
    op.drop_table('nf_news')
    op.drop_table('cl_roles')
    op.drop_table('cl_resource_type')
    op.drop_table('cl_parsers')
    op.drop_table('cl_categories')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
