"""data_migration

Revision ID: 0002
Revises: 0001
Create Date: 2024-08-12 18:14:45.639794

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    files_for_import = [
        # Классификаторы
        '1_cl_categories.sql',
        '1_cl_resource_type.sql',
        '1_cl_parsers.sql',
        '1_cl_roles.sql',
    ]
    for file_name in files_for_import:
        with open(os.path.join('data', file_name), 'r') as file:
            op.execute(file.read())

    conn = op.get_bind()

    # Запрос для получения информации о последовательностях
    query = """
            SELECT
                table_name,
                column_name,
                column_default
            FROM
                information_schema.columns
            WHERE
                column_default LIKE 'nextval(%'
                AND table_schema = 'public'
        """

    # Выполнение запроса
    result = conn.execute(text(query))

    for row in result:
        table_name = row[0]
        column_name = row[1]
        column_default = row[2]

        # Извлечение имени последовательности из column_default
        seq_name = column_default.split("'")[1]

        # Получение максимального значения из таблицы
        max_query = f"SELECT COALESCE(MAX({column_name}), 0) FROM {table_name}"
        max_result = conn.execute(text(max_query)).scalar()

        # Установка значения последовательности
        setval_query = f"SELECT setval('{seq_name}', {max_result + 1}, false)"
        conn.execute(text(setval_query))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
