"""data_migration

Revision ID: 0002
Revises: 0001
Create Date: 2024-08-12 18:14:45.639794

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    files_for_import = [
        '2_TESTING_nf_resource.sql',
    ]
    for file_name in files_for_import:
        with open(os.path.join('data', file_name), 'r') as file:
            op.execute(file.read())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
