"""description_is_nullable

Revision ID: 0004
Revises: 0003
Create Date: 2024-08-16 17:55:58.234262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nf_news', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Краткий анонс новости')
    op.drop_constraint('nf_remote_categories_url_key', 'nf_remote_categories', type_='unique')
    op.create_unique_constraint(None, 'nf_resources', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nf_resources', type_='unique')
    op.create_unique_constraint('nf_remote_categories_url_key', 'nf_remote_categories', ['url'])
    op.alter_column('nf_news', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Краткий анонс новости')
    # ### end Alembic commands ###
