"""add_parse_at_field_to_news

Revision ID: 0004
Revises: 0003
Create Date: 2024-08-24 21:15:51.767925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nf_news', sa.Column('parsed_at', sa.DateTime(), nullable=True, comment='Дата когда новость была полностью спашена'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nf_news', 'parsed_at')
    # ### end Alembic commands ###
