"""rename_field

Revision ID: 0005
Revises: 0004
Create Date: 2024-08-28 18:41:45.846238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nf_remote_categories','news_resource_id', new_column_name='resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nf_remote_categories','resource_id', new_column_name='news_resource_id')
    # ### end Alembic commands ###
